# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog do Gustavo Veloso
tagline:          'Posts aleatórios sobre carreira, tecnologia e empreendedorismo'
description:      'Espaço para compartilhar ideias sobre carreira, tecnologia e empreendedorismo. Você também pode me encontrar no <a href="http://linkedin.com/in/gustavoveloso" target="_blank">LinkedIn</a> e no <a href="http://twitter.com/gjmveloso">Twitter<a/>.'
url:              http://www.gustavoveloso.com
baseurl:	  /

author:
  name:           'Gustavo Veloso'
  url:            http://twitter.com/gjmveloso

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

kramdown:
  input: GFM

