exclude: [vendor]
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            My Thoughts
tagline:          'Random posts about career, technology and entrepreneurship'
description:      'Space to share thoughts about career, technology and entrepreneurship. I can also be found at <a href="http://linkedin.com/in/gustavoveloso" target="_blank">LinkedIn</a> and <a href="http://twitter.com/gjmveloso">Twitter<a/>.'
url:              http://www.gustavoveloso.com
baseurl:	        /
timezone:         America/Santiago

author:
  name:           'Gustavo Veloso'
  url:            http://twitter.com/gjmveloso

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
